### ISSUE TITLE
plot rms in map view

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy#102]
Dear all,

Is there any attribute to control plot only impedance or tipper in the map view of rms? when I plot rms values on the map all of components are shown.

Best Regards,
Mohammad

**Comment by brenmous** [comment]
Hi Mohammad,

Sorry for the delay in getting back to you. I'm working on some features of plotting at the moment and want to solve this issue for you while I'm at it.

Unfortunately I'm not an MT scientist and new to the mtpy code, so I'm afraid I might not be working with the correct plot. Could you please send me an example of the script you use to generate this RMS map? 

Thank you for your patience. Also know that the plot penetration depth bug you emailed about will also be worked on soon.

Kind regards,
Bren

**Comment by kashkoulimohammad** [comment]
Hi Bern,
Thank you for following the issues.
For sure, I put the script that I used for plot.
`import os
import os.path as op
import numpy as np

#os.chdir(r'C:\mtpywin\mtpy')

from mtpy.modeling.modem import PlotRMSMaps
#from mtpy.imaging.plot_rms_map import PlotRMSMaps


wd = r'/home/mkash/mtpy-develop/mtpy-develop/examples/model_files/ModEM_2'
savepath = r'/home/mkash/mtpy-develop/mtpy-develop/examples/model_files/ModEM_2'



filestem = op.join(wd,'Modular_MPI_NLCG_061')
resid_fn=op.join(wd,filestem + '.res')

probj = PlotRMSMaps(resid_fn,
                    period_index='all',
                    rms_cmap='jet', # choose matplotlib colormap or set to None
                    rms_max=5
                    )
probj.save_figure(save_path=savepath,
                  save_fig_dpi = 300 # change to your preferred figure resolution
                  )`

**Comment by brenmous** [comment]
Thanks Mohammad, I've added these options and additional features.

The changes are currently in testing on branch [bren-rmsbasemap+shapefiles](/MTgeophysics/mtpy/tree/bren-rmsbasemap+shapefiles), once they're tested they'll be merged to the main develop branch. 

I'll also be looking into the plot penetration depth bug and will keep you updated through issue #104
