### ISSUE TITLE
mtpy Python3.7

### ISSUE THREAD

**Issue by JuanjoLedo** [MTgeophysics/mtpy#112]
Hello, I was following the installation guide for windows 10 in the wiki section _(https://github.com/MTgeophysics/mtpy/wiki/MTPy-installation-guide-for-Windows-10-and-Ubuntu-18.04)_ 
But it looks that mtpy is not python3.7 ready, it was given me some problems with the print command when I was trying to run mtpy commands, is that correct? 
Could you tell me which version of Anaconda and python should be installed on a windows 10 system to run the last mtpy version?

Thank you very much

**Comment by alkirkby** [comment]
Could you please copy and paste your code and the error message? We recently converted MTPy to Python 3, there may be some remaining errors in there so are happy to fix them if we know where they are.
Thanks, Alison.

**Comment by JuanjoLedo** [comment]
Thank you Alison,

I was trying to run the plot_phase_tensor_map.py that is in \mtpy\examples\scripts.
 I changed the path to the data directory (mtpy\examples\data\edi_files_2) and commented line 62 about the background image.

This is the error I get

********
_runfile('C:/Users/Juanjo Ledo/mtpy/examples/scripts/plot_phase_tensor_map.py', wdir='C:/Users/Juanjo Ledo/mtpy/examples/scripts')
Traceback (most recent call last):

  File "C:\Users\Juanjo Ledo\mtpy\examples\scripts\plot_phase_tensor_map.py", line 16, in <module>
    import mtpy.imaging.phase_tensor_maps as pptmaps

ModuleNotFoundError: No module named 'mtpy.imaging.phase_tensor_maps'_

Thank you very much

**Comment by JuanjoLedo** [comment]
When I do a pip list on the mtpy terminal  the version that I get is "mtpy 0.0.1", I guess that is still trying to use the previous version I have installed of mtpy.

I tried  a fresh "pip mtpy install" but it says 
"Requirement already satisfied: mtpy in c:\users\juanjo ledo\programas\mtpy-master (0.0.1)"

thank you, best regards
