### ISSUE TITLE
Error in Impedance function set_res_phase

### ISSUE THREAD

**Issue by El-minadero** [MTgeophysics/mtpy#119]
Building a Z tensor from phase, resistivity and their respective errors is bugged when using ```set_res_phase```

```python
impedance = Z()
impedance.set_res_phase(app_resistivity, phase, frequency_array,app_err,phase_err)
```

where ```app_resistivity```, ```phase```, ```app_err```, ```phase_err```, are all shaped (30,2,2). frequency array is shaped (30), yet I'm getting a broadcast error in ```z.py``` line 73:
```
File "../anaconda3/envs/mtpy/lib/python3.7/site-packages/mtpy/core/z.py", line 173, in set_res_phase
abs_z = np.sqrt(5.0 * self.freq * self.resistivity)

ValueError: operands could not be broadcast together with shapes (30,) (30,2,2)
```

**Comment by alkirkby** [comment]
Hi, I've just fixed this broadcasting error. See how you go.
