### ISSUE TITLE
freq_tol function when creating Occam2D/Mare2D data files

### ISSUE THREAD

**Issue by katerob31** [MTgeophysics/mtpy#135]
In the Occam2D.py - there is an freq_tol variable (a frequency tolerance as a percentage). This freq_tol is there so that if you have masked certain frequencies in your data, you have control over whether the data are interpolated at this frequency (or the given frequencies) or left without data at this frequency.  At the moment, I can only produce occam (and subsequently Mare2D) using the develop branch when there is no freq_tol set. In other words, if I've masked data so that there is a gap, when I produce the occam data file the gap is always filled. Perhaps an alternative is interpolate_freq, but I'm not sure that the interpolate_freq (true,false) is still working in the latest version when generating a data file.

**Comment by alkirkby** [comment]
I have just pushed  a potential fix to the branch mare2d_updates. For me, freq_tol was not working i.e. i got an error when I tried to run it. Please test and let me know if this fixes the problem.

**Comment by katerob31** [comment]
Works perfectly. Thanks so much!
