### ISSUE TITLE
PlotResPhaseMaps with a list of MT objects

### ISSUE THREAD

**Issue by agrayver** [MTgeophysics/mtpy#137]
Is it possible to pass a list of MT objects to the PlotResPhaseMaps instead of edi files (similar to PlotPhaseTensorMaps)?

**Comment by alkirkby** [comment]
Not at the moment but it should be an easy fix. I will try and get to this today

**Comment by alkirkby** [comment]
I added this functionality, you can provide an mt object list through the variable mt_list when creating the PlotResPhaseMaps object. I also added an example in examples/scripts, the option to feed in an mt object list is commented out. Hope this helps

**Comment by agrayver** [comment]
Thank you, Alison, this works and is very helpful!
