### ISSUE TITLE
Using MTpy for data files in .dat format

### ISSUE THREAD

**Issue by roshanmanjitsingh** [MTgeophysics/mtpy#140]
I have an MT data file where the entries (impedance and the standard errors) are in column format.
Period Re(Zxx) Im(Zxx) Error (Zxx) ......Re(Zyy) Im(Zyy) Error(Zyy)

1) Can I use MTpy directly for this format?
2) Do I need to convert the column format file into EDI format before using MTpy.

Please suggest me the required steps.

**Comment by alkirkby** [comment]
At the moment I think the best way to do this is to convert to an EDI file which from issue #139 it looks like you've managed to do.
