### ISSUE TITLE
Removing elements from edi_collection

### ISSUE THREAD

**Issue by agrayver** [MTgeophysics/mtpy#142]
Is there a legitimate way to remove stations from an edi_collection? By "legitimate" I mean a way that does not break internal integrity of the collection.

**Comment by zhang01GA** [comment]
I do not think we have implemented a dynamic removal of stations. We simply assume the station edi files is a static list.
one can manipulate the input EDI file folder, so that some edi files can be excluded from the very beginning of processing.

Hope this answered your question?

**Comment by agrayver** [comment]
Thanks, this clarifies the interface.
