### ISSUE TITLE
Modify and update colorscale for the sounding curve using GUI

### ISSUE THREAD

**Issue by roshanmanjitsingh** [MTgeophysics/mtpy#145]
I want to change the default color of the tipper arrows and the phase tensor ellipses in the plot.
A GUI appears which shows the option to change the color but when I am trying to change the color only the axes color changes but the phase tensor ellipse color showing phi(max) and the color for the arrow of the tipper are not changing.
I kindly request you to help me with this issue.

Best Regards
Roshan Kumar Singh

**Comment by snazzybloke** [comment]
@roshanmanjitsingh, probably the easiest way to customize the plots is to modify the value of the attributes of the object (pt_obj in your script) and redraw it, e.g.: 

```python
mt_obj = MT(edi_file)
pt_obj = mt_obj.plot_mt_response(plot_num=2, 
plot_tipper = 'yri',
plot_pt = 'y')
pt_obj.arrow_color_imag = 'r'
pt_obj.arrow_color_real = 'g'
pt_obj.ellipse_cmap = 'viridis'
pt_obj.redraw_plot()
pt_obj.save_plot(os.path.join(savepath,"Tris26.png"), fig_dpi=400)
```
Let me know if this works for you.

**Comment by roshanmanjitsingh** [comment]
@snazzybloke Thanks it worked fine for me.
