### ISSUE TITLE
installation script bin/conda_setup_mtpy_win.bat not working 

### ISSUE THREAD

**Issue by zhang01GA** [MTgeophysics/mtpy#23]
double click, the default mtpy env was created somewhere we cannot see.

run in cmd window, it create in current working dir but still cannot see 
$ conda info --env
# conda environments:
#
bayesml                  C:\Anaconda2\envs\bayesml
myenv                    C:\Anaconda2\envs\myenv
root                  *  C:\Anaconda2

please provide a step-by-step guide as how to use the bat script

then start the MTgui use the new env ?

**Comment by YingzhiGou** [comment]
strange, do you have multiple conda installed?

in theory, when the default environment is created, you should be able to start the gui using bin\start_gui.bat

i will test it again on windows 10

**Comment by YingzhiGou** [comment]
there is a typo in the script, and it is fixed now, could you test?

**Comment by zhang01GA** [comment]
I will ask Sudhir to re-test it  @sudhirJain

**Comment by sudhirJain** [comment]
I have tested conda_setup_mtpy_win.bat.  mtpy has been installed in virtual environment. Following are the results.
C:\dev\venv\satellite\mtpy\bin>conda info --envs
# conda environments:
#
Seismic_Phases           C:\dev\miniconda2\envs\Seismic_Phases
mtpy                     C:\dev\miniconda2\envs\mtpy
testsat                  C:\dev\miniconda2\envs\testsat
root                  *  C:\dev\miniconda2

C:\dev\venv\satellite\mtpy\bin>conda info --envs
# conda environments:
#
Seismic_Phases           C:\dev\miniconda2\envs\Seismic_Phases
mtpy                     C:\dev\miniconda2\envs\mtpy
testsat                  C:\dev\miniconda2\envs\testsat
root                  *  C:\dev\miniconda2


** activating mtpy virtual enviornment

C:\dev\venv\satellite\mtpy\bin>activate mtpy

** Starting GUI

(mtpy) C:\dev\venv\satellite\mtpy\bin>start gui
The system cannot find the file gui.

(mtpy) C:\dev\venv\satellite\mtpy\bin>start_gui.bat
calling activate mtpy
