### ISSUE TITLE
Suggested clean-up of examples directory

### ISSUE THREAD

**Issue by alkirkby** [MTgeophysics/mtpy#27]
I'm going through the examples directory. I will test (and fix as necessary) all the example scripts, currently found in mtpy/scripts. I've got some comments on the structure of this directory, which I'd like to put out for comment before I make changes:

1. There seem to be two locations for example scripts (mtpy/scripts and mtpy/examples/tests), notebooks (mtpy/notebooks and mtpy/examples/notebooks) and data (mtpy/data and mtpy/examples/data). If others are happy for me to do so, I will move these all to the examples directory. Also, please let me know if you have scripts or data somewhere else.

2. I'm not sure the value of having example plots - when I looked in the examples/plots directory I expected to find scripts to make plots. I was thinking of structuring the examples directory a bit like mtpy, e.g. with folders analysis, core, imaging, etc containing examples for the relevant modules, with an additional folder for the data and perhaps some example images.

**Comment by rh-downunder** [comment]
Would be great to have a central location for all the example scripts, notebooks and related data. I think it would be better to have just one folder for data, if some of the scripts are using the same data in different contexts.
