### ISSUE TITLE
gis_tools.py failed unittesting

### ISSUE THREAD

**Issue by zhang01GA** [MTgeophysics/mtpy#29]
Recent changes to mtpy/utils/gis_tools.py has been failing unit tests

## Possible Solution 
Debug the gis_tools.py
or 
check and modify the test script tests/utils/test_gis_tools.py

## Steps to Reproduce (for bugs)
<u25656@PC-62907 MINGW32 /e/Githubz/mtpy (develop)
$ export GDAL_DATA=/c/Anaconda2/Library/share/gdal

u25656@PC-62907 MINGW32 /e/Githubz/mtpy (develop)
$ py.test.exe tests/utils/test_gis_tools.py

**Comment by rh-downunder** [comment]
I've just pushed a fix to both test_gis_tools.py and gis_tools.py, which should resolve this issue.

**Comment by rh-downunder** [comment]
Done.
