### ISSUE TITLE
phase tensor maps from edi files - duplication

### ISSUE THREAD

**Issue by alkirkby** [MTgeophysics/mtpy#33]
I found another duplicated module:
mtpy.imaging.phase_tensor_maps and
mtpy.imaging.plotptmaps

These both make phase tensor maps from edi files.
I think mtpy.imaging.phase_tensor_maps is the most up to date.

Can we move plotptmaps to legacy or is there functionality that needs to be moved across first?

**Comment by zhang01GA** [comment]
I agree with Alison:  the mtpy/imaging/phase_tensor_maps.py is more updated and it is working.

The mtpy/imaging/plotptmaps.py has less usage.  Can be moved to legacy. I will do it now.

**Comment by rh-downunder** [comment]
Thanks Fei. I was wondering if we should make a distinction between functionality for plotting modelled phase tensors and those from edi files, by naming the files differently -- perhaps rename `phase_tensor_maps` to `data_phase_tensor_maps`? Ideally, it would be best to refactor these functionality into one file, but it will take quite a bit of work to make sure both sets of functionality are seamlessly merged.

**Comment by zhang01GA** [comment]
Alison, you are right, I did notice similar plottings for edi files and modelled data file. Let's have a good overall look and think/design before  jumping into the code.

**Comment by alkirkby** [comment]
Yes I agree, we need to make a distinction between phase tensor maps from edi files (or from impedance - as PlotPhaseTensorMaps has the option to provide z_object_list also) and from ModEM. Ultimately they should be merged, as the functionality is basically the same (it's only the reading in of data that needs to be different). I think leave phase_tensor_maps as it is and the modem one can stay as modem_phase_tensor_maps, and maybe we can do a similar thing with other functionality (e.g. rename plot_response to modem_plot_response) and functions to plot modem slices to imaging.modem_plot_slice. Thoughts?
