### ISSUE TITLE
General Error

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy#72]
Dear all,
I install MTpy on the Ubuntu 18.04.1 LTS. During install when I test test_ediCollection.py with pytest it worked correctly but now I can not run anything with python on my data or MTpy data that exist in data folder. I download last version. As fallows are some error that I have. Unfortunately I can not run anythings.
 
git version 2.17.1
Python 2.7.15rc1

python plotresponse.py
Traceback (most recent call last):
  File "plotresponse.py", line 23, in <module>
    import mtpy.imaging.mtcolors as mtcl
ImportError: No module named mtpy.imaging.mtcolors

python plot_edis.py 
Traceback (most recent call last):
  File "plot_edis.py", line 15, in <module>
    from mtpy.core import mt
ImportError: No module named mtpy.core

python -OO start.py
Traceback (most recent call last):
  File "start.py", line 30, in <module>
    from mtpy.core.edi_collection import EdiCollection
ImportError: No module named mtpy.core.edi_collection

**Comment by alkirkby** [comment]
Hi - this looks like an installation issue. Can you try running the following from your mtpy installation directory?

python setup.py develop --user

**Comment by kashkoulimohammad** [comment]
Thank you for replying.
My problem was solved.
