### ISSUE TITLE
Generalizing language to include if use on a Mac is working

### ISSUE THREAD

**Issue by JKutt** [MTgeophysics/mtpy#77]
Suggesting the mention if only to be used explicitly on Windows or Linux.

openjournals/joss-reviews#1358

**Comment by JKutt** [comment]
Installation on a Mac can be accomplished by following the Linux install instructions.

**Comment by alkirkby** [comment]
I've updated the link on the Wiki page to the Linux installation instructions to say that it is for Linux or Mac users
