### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by JKutt** [MTgeophysics/mtpy#78]
Found two documents on installation process, one looks used for users and the other for developer. Initially tried the development method but get errors when trying to import `mtpy.core.mt` saying GDAL is not properly configured and passing that get `AttributeError: module 'pyproj' has no attribute 'pyproj_datadir'`. The second installation from the PDF indicates Git Bash be used. Would like to avoid installing additional Git tools. A general way to edit the bashrc files would be beneficial.

openjournals/joss-reviews#1358

**Comment by JKutt** [comment]
I managed to follow the Linux installation and got a bit further on the installation.

**Comment by zhang01GA** [comment]
Thanks a lot JKutt for review and test the software. We are working to resolve the issues.

1) the developer installation guide in the README page has been removed. 
2)Only the WikiPages: https://github.com/mtgeophysics/mtpy/wiki contains installation guide.
3) Which PDF did you refer to in your comments above? We guess you mean the wiki pages?

**Comment by JKutt** [comment]
No problem! Thanks for the clarification. The PDF I was referring to was `MTPy User Guide.pdf`. I found it under Docs.

**Comment by zhang01GA** [comment]
The docs/MTPy User Guide.pdf  is PDF format of workshop tutorial material. 
In its introduction there are two URLs pointing to a detailed online docs (module API interfaces) and the Wiki page of installation guide: A user must first go through the wiki page installation guide before doing the test run of the modules in the MTPy User Guide.pdf.

Please let me know if this is clarified now. Thanks

**Comment by zhang01GA** [comment]
Hi JButt, 
We have pushed in a commit today to fix an issue related to pyproj installation version-incompatibility.
Please git pull the latest version from develop branch, to do  further testing. 
The wiki page installation guide for Windows has been updated to reflect the new change. In particular the configuration part no longer need to include the export PROJ_LIB=... 

Please let us know if you can install successfully and run some test scripts. For instance:
**python examples/scripts/plot_edis.py**
--

**Comment by zhang01GA** [comment]
> Found two documents on installation process, one looks used for users and the other for developer. Initially tried the development method but get errors when trying to import `mtpy.core.mt` saying GDAL is not properly configured and passing that get `AttributeError: module 'pyproj' has no attribute 'pyproj_datadir'`. The second installation from the PDF indicates Git Bash be used. Would like to avoid installing additional Git tools. A general way to edit the bashrc files would be beneficial.
> 
> [openjournals/joss-reviews#1358](https://github.com/openjournals/joss-reviews/issues/1358)

Re git bash installation in Windows. It is simply a recommendation of using mtpy easily, as it is our preference.  In principle, a user does not have to install git-bash, just have python2.7/3.6 and with mtpy package + dependencies installed, then you should be able to use the mtpy modules. Hope this clarify your question.

**Comment by JKutt** [comment]
> Hi JButt,
> We have pushed in a commit today to fix an issue related to pyproj installation version-incompatibility.
> Please git pull the latest version from develop branch, to do further testing.
> The wiki page installation guide for Windows has been updated to reflect the new change. In particular the configuration part no longer need to include the export PROJ_LIB=...
> 
> Please let us know if you can install successfully and run some test scripts. For instance:
> ## **python examples/scripts/plot_edis.py**

All is working. The script `plot_edis.py` runs, plots, saves images.

**Comment by JKutt** [comment]
> > Found two documents on installation process, one looks used for users and the other for developer. Initially tried the development method but get errors when trying to import `mtpy.core.mt` saying GDAL is not properly configured and passing that get `AttributeError: module 'pyproj' has no attribute 'pyproj_datadir'`. The second installation from the PDF indicates Git Bash be used. Would like to avoid installing additional Git tools. A general way to edit the bashrc files would be beneficial.
> > [openjournals/joss-reviews#1358](https://github.com/openjournals/joss-reviews/issues/1358)
> 
> Re git bash installation in Windows. It is simply a recommendation of using mtpy easily, as it is our preference. In principle, a user does not have to install git-bash, just have python2.7/3.6 and with mtpy package + dependencies installed, then you should be able to use the mtpy modules. Hope this clarify your question.

Clarified, thanks.
