### ISSUE TITLE
docstrings not showing up on website

### ISSUE THREAD

**Issue by lheagy** [MTgeophysics/mtpy#80]
(related to the JOSS review openjournals/joss-reviews#1358)

Currently, the docstrings describing the modules are not displaying online. For example:
https://mtpy2.readthedocs.io/en/develop/core.html
![image](https://user-images.githubusercontent.com/6361812/57027673-e5e82f00-6bf1-11e9-8ff7-f54788c32017.png)

Also, I saw that you have a user-guide in the docs directory, but this isn't easily findable from the docs website. It might be worth including a link on the main documentation page.

**Comment by alkirkby** [comment]
This has now been fixed - documentation is compiling correctly now and a link to the user guide has been added to the front page.
