### ISSUE TITLE
Occam2D build input file

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy#81]
Dear all,
I am trying build input files for Occam2D code. My length profile is 16 km with 62 stations but when I build input files the MTpy projected stations at profile with 4 km length. I have considered minimum distance of stations for cell width and chosen enough layers.   

Regards,
Mohammad

**Comment by zhang01GA** [comment]
could you provide more details. I guessed that you'd like smaller cell size?

**Comment by kashkoulimohammad** [comment]
these are my code for mesh and model:
`ocr = occam2d.Regularization(ocd.station_locations)
ocr.n_layers = 90
ocr.cell_width = 150
ocr.num_x_pad_cells = 10
ocr.x_pad_multiplier = 1.3
ocr.trigger= 0.25
`
Also I have tried with other values that had same result.
![Projected_Profile](https://user-images.githubusercontent.com/11463583/57747664-5b8cda00-768b-11e9-857c-5ee811a5738f.png)

**Comment by kujaku11** [comment]
By default Occam2D.Data projects stations onto a profile line that is perpendicular to estimated strike.  That's why your line is smashed.  To undo that use the key occam2d.Data._rotate_to_strike = False.  Or set the geoelectric strike angle to 0.

**Comment by kashkoulimohammad** [comment]
Thanks.
Is there way that set mesh regard to stations distance? In Occam2D stations location must be on the vertical node.
