### ISSUE TITLE
AttributeError: 'Z' object has no attribute '_compute_res_phase'

### ISSUE THREAD

**Issue by bernard-giroux** [MTgeophysics/mtpy#92]
Calling estimate_static_spatial_median in staticshift.py does not work

<Example code:

```python
# Paste your code here
edi = '/Users/giroux/CloudStation/Encadrement/PhD_Hassan/test_mtpy/108A08-a_ss.edi'
import mtpy.analysis.staticshift as st
st.estimate_static_spatial_median(edi)

```

results in

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/giroux/GitHub/mtpy/mtpy/analysis/staticshift.py", line 87, in estimate_static_spatial_median
    mt_obj.Z._compute_res_phase()
AttributeError: 'Z' object has no attribute '_compute_res_phase'
```

## Your Environment

  * Operating system:
  * MtPy version: current in master branch
  * Python version: 3.7.4

  * Matplotlib version:
  * Matplotlib backend (`print(matplotlib.get_backend())`):

  * QT version:

**Installed Python Packages:**
use `pip freeze` or `conda list [-n ENVIRONMENT_NAME]` to list all the installed libraries.

alabaster==0.7.12
altgraph==0.16.1
anytree==2.6.0
appdirs==1.4.3
appnope==0.1.0
apptools==4.4.0
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
basemap==1.2.0
bleach==3.1.0
Bottleneck==1.2.1
Cartopy==0.17.0
certifi==2019.6.16
chardet==3.0.4
cloudpickle==1.2.1
configobj==5.0.6
cycler==0.10.0
Cython==0.29.13
decorator==4.4.0
defusedxml==0.6.0
docutils==0.15
entrypoints==0.3
envisage==4.7.0
flake8==3.7.8
funcsigs==1.0.2
future==0.17.1
GDAL==3.0.1
gdbm==3.7.4
geographiclib==1.49
h5py==2.9.0
idna==2.8
imagesize==1.1.0
importlib-metadata==0.19
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.1
jsonschema==3.0.2
jupyter-client==5.3.1
jupyter-core==4.5.0
keyring==19.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
llvmlite==0.29.0
lxml==4.3.2
macholib==1.11
MarkupSafe==1.1.1
matplotlib==3.1.1
mayavi==4.6.2
mccabe==0.6.1
meshio==2.3.3
mistune==0.8.4
mock==3.0.5
modulegraph==0.17
more-itertools==7.2.0
mpmath==1.1.0
nbconvert==5.5.0
nbformat==4.4.0
netCDF4==1.2.9
nose==1.3.7
notebook==6.0.1
numba==0.45.1
numexpr==2.7.0
numpy==1.17.1
numpydoc==0.9.1
obspy==1.1.0
olefile==0.46
OWSLib==0.17.0
packaging==19.1
pandas==0.25.1
pandocfilters==1.4.2
parso==0.5.1
patsy==0.5.1
pbr==5.4.2
pep8-naming==0.7.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pipdate==0.3.2
pkgconfig==1.5.1
pluggy==0.12.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
py2app==0.19
pycairo==1.18.1
pycodestyle==2.5.0
pyepsg==0.3.2
pyface==6.0.0
pyFFTW==0.10.4
pyflakes==2.1.1
Pygments==2.4.2
pygmsh==6.0.2
pylint==2.3.1
pyobjc-core==5.2
pyobjc-framework-Cocoa==5.2
pyparsing==2.2.0
pyproj==2.3.1
pyrsistent==0.15.4
pyshp==1.2.12
pytest==5.1.2
pytest-runner==4.4
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
pyzmq==18.1.0
QtAwesome==0.6.0
qtconsole==4.5.2
QtPy==1.9.0
requests==2.22.0
roman==3.2
rope==0.14.0
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
setuptools-scm==3.3.3
Shapely==1.6.4
simplegeneric==0.8.1
sip==4.19.18
six==1.12.0
snowballstemmer==1.9.0
spectrum==0.7.5
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.3.8
statsmodels==0.10.1
sympy==1.4
tables==3.5.2
terminado==0.8.2
testpath==0.4.2
tkinter==0.0.0
tornado==6.0.3
traitlets==4.3.2
traits==4.6.0
traitsui==6.0.0
typed-ast==1.4.0
urllib3==1.25.3
vcversioner==2.16.0.0
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.2
wurlitzer==1.0.2
zipp==0.6.0

**Comment by kujaku11** [comment]
Fixed.
