### ISSUE TITLE
Plot ModEM response in 2 columns

### ISSUE THREAD

**Issue by kashkoulimohammad** [MTgeophysics/mtpy#93]
Dear all,

I tried to plot ModEM response but I could not plot in 2 columns and these errors happened:
```
Traceback (most recent call last):
  File "plot_response.py", line 20, in <module>
    ro.plot()
  File "/home/mkash/.local/lib/python3.7/site-packages/mtpy/modeling/modem/plot_response.py", line 199, in plot
    self._plot_2col()
  File "/home/mkash/.local/lib/python3.7/site-packages/mtpy/modeling/modem/plot_response.py", line 1947, in _plot_2col
    legend_ax_list = self.ax_list[0:self.plot_component / 2]
TypeError: slice indices must be integers or None or have an __index__ method
```
I

**Comment by alkirkby** [comment]
I've pushed an update that should fix this issue in the example script. Let me know if you have any more issues.

**Comment by kashkoulimohammad** [comment]
@alkirkby Thank you.
I installed mtpy by pip. Will it apply in pip package?

**Comment by alkirkby** [comment]
Sorry no it won't unfortunately as the pip package is a static release. That will have to wait until our next release. If you want the update immediately I'd recommend using the instructions on our wiki page: https://github.com/MTgeophysics/mtpy/wiki

**Comment by kashkoulimohammad** [comment]
Dear Dr. Kirkby,

In the static version, outputs of phase tensor section for station name write extra characters. For instance, instead of MT104 write b'MT104'.
![l5_skew_n2](https://user-images.githubusercontent.com/11463583/76024500-7f821a80-5f40-11ea-81b2-42fde2964eb5.png)
Regards,
